app = "taskmaster-api"   # your app name on Fly

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"          # Fly expects you to expose this port

[[services]]
  internal_port = 8080   # must match process.env.PORT
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
